
const content = {
    landingPageTitle: 'Messages',
    landingPageMessage: 'Got an enquiry? Send a message to the Team at B - we’re here to help. What’s more, because you’re logged in, these messages are safe and secure. Messages are displayed going back 13 months.',
    inboxPageTitle: 'Inbox message',
    sentPageTitle: 'Sent message',
    newMessagePageTitle: 'New message',
    replyMessageTitle: 'Reply',
    back: 'Back',
    send: 'Send',
    maxCharLimit: 'Maximum character limit is three thousand',
    message: 'Message',
    messageRelatesTo: 'Message relates to',
    subject: 'Subject',
    messageSent: 'Message sent',
    ok: 'OK',
    draftBody: 'Message saved as a draft',
    leaveMessageHeading: 'Your message hasn’t been sent yet',
    returnToMessage: 'Return to message',
    saveDraft: 'Save Draft',
    leaveMessageBody: 'If you leave the message now it won’t be saved.',
    charLeft: 'Characters Left:',
    sorryHeader: 'Sorry, there’s been a technical problem',
    tryAgain: 'It looks like something has gone wrong in the background. Please try again.',
    getInTouch: 'If you’re still having problems, please get in touch.',
    retry: 'Retry',
    leavePage: 'Leave page',
};

export default content;