
const content = {
	DYB: {
		landingPageTitle: 'Messages',
		landingPageMessage: "If you want to ask us a question relating to your accounts or products you can send us a secure message and we will respond with the help you need.  We may also send you secure messages to let you know about your new letters and documents. For urgent queries please call us.",
		inboxPageTitle: 'Inbox Message',
		sentPageTitle: 'Sent Message',
		archivePageTitle: 'Archive Message',
		newMessagePageTitle: 'New secure message',
		replyMessageTitle: 'Reply',
		draftMessageTitle: 'Draft',
		back: 'Back',
		send: 'Send message',
		maxCharLimit: 'Maximum character limit is three thousand',
		message: 'Message',
		messages: 'Secure messages',
		messageRelatesTo: "What account's it about?",
		subject: 'Subject',
		messageSent: 'Message sent',
		messageDeleted: 'Message deleted',
		messageArchived: 'Message has been archived.',
		messageUnarchived: 'Message moved back to inbox.',
		ok: 'OK',
		draftBody: 'Message saved as draft',
		leaveMessageHeading: "Oops, your message hasn't sent yet",
		returnToMessage: 'Continue with message',
		saveDraft: 'Save draft',
		leaveMessageBody: "Sure you want to leave this page? If you do, your message won't be sent or saved as a draft.",
		charLeft: 'characters left',
		sorryHeader: "Something's gone wrong",
		tryAgain: "Hmm. Looks like there's been a technical problem. Why not give it another go?",
		getInTouch: 'Still not working? Try another way to get in touch with the team at B.',
		retry: 'Try again',
		leavePage: 'Leave page',
		accError: "Oops. You'll have to choose what account your message is about. General enquiry? Just choose ‘No specific account'.",
		subError: "Oops. You'll have to choose a subject for your secure message. ",
		newSecureMessage: 'New secure message',
		thatsallTextInbox: "That's all of them. Any new messages the team at B send you will show at the top of your inbox. Remember that only messages from the last 3 years are shown here.",
		thatsallTextDraft: "That's all of them. Any new messages you save will show at the top of your drafts. Remember that only messages from the last 3 years are shown here.",
		thatsallTextSend: "That's all of them. Any new messages you send will show at the top of your sent items. Remember that only messages from the last 3 years are shown here.",
		thatsallTextArchived: "That's all of them. Any new messages you archive will show at the top of your archived items. Remember that only messages from the last 3 years are shown here.",
		noMessages: 'No messages.',
		deleteMessageHeading: 'Sure you want to delete this message?',
		deleteMessageBody: "If you delete this message now, you won't be able to get it back.",
		dontDelButton: "No, don't delete",
		delButton: 'Yes, delete',
		messageVal: 'Oops. Looks like your message has gone over the character limit. Try and cut it down a little then give it another go',
		showMore: 'Show more messages',
		backToAccounts: 'Back to accounts',
		pleaseSelect: 'Please select',
		editSavedMessage: 'Edit saved message',
		noSpecificAccount: 'No specific account',
		threeCharLeft: 'Three characters left',
		oneCharLeft: 'One character left',
		maxCharLeft: 'Maximum characters limit reached',
		delete: 'Delete',
		unread: 'Unread',
		archive: "Archive",
		unarchive: "Unarchive",
		moveToInbox: 'Move to inbox',
		replyUnread: 'Reply Unread',
		deleteUnread: 'Delete Unread',
		pending: 'Pending',
		sendingMessage: "Sending message...",
		savingMessage: "Saving draft...",
	},
	VM: {
		landingPageTitle: 'Messages',
		landingPageMessage: "If you want to ask us a question relating to your accounts or products you can send us a secure message and we will respond with the help you need.  We may also send you secure messages to let you know about your new letters and documents. For urgent queries please call us.",
		inboxPageTitle: 'Inbox Message',
		sentPageTitle: 'Sent Message',
		archivePageTitle: 'Archive Message',
		newMessagePageTitle: 'New secure message',
		replyMessageTitle: 'Reply',
		draftMessageTitle: 'Draft',
		back: 'Back',
		send: 'Send message',
		maxCharLimit: 'Maximum character limit is three thousand',
		message: 'Message',
		messages: 'Secure messages',
		messageRelatesTo: "What account's it about?",
		subject: 'Subject',
		messageSent: 'Message sent',
		messageDeleted: 'Message deleted',
		messageArchived: 'Message has been archived.',
		messageUnarchived: 'Message moved back to inbox.',
		ok: 'OK',
		draftBody: 'Message saved as draft',
		leaveMessageHeading: "Oops, your message hasn't sent yet",
		returnToMessage: 'Continue with message',
		saveDraft: 'Save draft',
		leaveMessageBody: "Sure you want to leave this page? If you do, your message won't be sent or saved as a draft.",
		charLeft: 'characters left',
		sorryHeader: "Something's gone wrong",
		tryAgain: "Hmm. Looks like there's been a technical problem. Why not give it another go?",
		getInTouch: 'Still not working? Try another way to get in touch with the team at B.',
		retry: 'Try again',
		leavePage: 'Leave page',
		accError: "Oops. You'll have to choose what account your message is about. General enquiry? Just choose ‘No specific account'.",
		subError: "Oops. You'll have to choose a subject for your secure message. ",
		newSecureMessage: 'New secure message',
		thatsallTextInbox: "That's all of them. Any new messages the team at B send you will show at the top of your inbox. Remember that only messages from the last 3 years are shown here.",
		thatsallTextDraft: "That's all of them. Any new messages you save will show at the top of your drafts. Remember that only messages from the last 3 years are shown here.",
		thatsallTextSend: "That's all of them. Any new messages you send will show at the top of your sent items. Remember that only messages from the last 3 years are shown here.",
		thatsallTextArchived: "That's all of them. Any new messages you archive will show at the top of your archived items. Remember that only messages from the last 3 years are shown here.",
		noMessages: 'No messages.',
		deleteMessageHeading: 'Sure you want to delete this message?',
		deleteMessageBody: "If you delete this message now, you won't be able to get it back.",
		dontDelButton: "No, don't delete",
		delButton: 'Yes, delete',
		messageVal: 'Oops. Looks like your message has gone over the character limit. Try and cut it down a little then give it another go',
		showMore: 'Show more messages',
		backToAccounts: 'Back to accounts',
		pleaseSelect: 'Please select',
		editSavedMessage: 'Edit saved message',
		noSpecificAccount: 'No specific account',
		threeCharLeft: 'Three characters left',
		oneCharLeft: 'One character left',
		maxCharLeft: 'Maximum characters limit reached',
		delete: 'Delete',
		unread: 'Unread',
		archive: "Archive",
		unarchive: "Unarchive",
		moveToInbox: 'Move to inbox',
		replyUnread: 'Reply Unread',
		deleteUnread: 'Delete Unread',
		pending: 'Pending',
		sendingMessage: "Sending message...",
		savingMessage: "Saving draft...",
	},

	CB: {
		landingPageTitle: 'Messages',
		landingPageMessage: "If you want to ask us a question relating to your accounts or products you can send us a secure message and we will respond with the help you need.  We may also send you secure messages to let you know about your new letters and documents. For urgent queries please call us.",
		inboxPageTitle: 'Inbox Message',
		sentPageTitle: 'Sent Message',
		archivePageTitle: 'Archive Message',
		newMessagePageTitle: 'New secure message',
		replyMessageTitle: 'Reply',
		draftMessageTitle: 'Draft',
		back: 'Back',
		send: 'Send message',
		maxCharLimit: 'Maximum character limit is three thousand',
		message: 'Message',
		messages: 'Secure messages',
		messageRelatesTo: 'Related account',
		subject: 'Subject',
		messageSent: 'Message sent',
		messageDeleted: 'Message deleted',
		messageArchived: 'Message has been archived.',
		messageUnarchived: 'Message moved back to inbox.',
		ok: 'OK',
		draftBody: 'Message saved as draft',
		leaveMessageHeading: "Your message hasn't been sent yet",
		returnToMessage: 'Continue with message',
		saveDraft: 'Save draft',
		leaveMessageBody: "If you leave this page now, your message won't be sent or saved as a draft.",
		charLeft: 'characters remaining',
		sorryHeader: "Sorry, there's been a technical problem",
		tryAgain: "It looks like something's gone wrong in the background. Please try again.",
		getInTouch: "If you're still having problems, please use another method to get in touch with us.",
		retry: 'Try again',
		leavePage: 'Leave page',
		accError: "Please select which account your message relates to. If it's a general enquiry, select 'No specific account'.",
		subError: 'Please select a subject for your secure message.',
		newSecureMessage: 'New secure message',
		thatsallTextInbox: "That's all of them. Any new messages we send you will appear at the top of your inbox. Please note that only messages from the last 3 years are displayed here.",
		thatsallTextDraft: "That's all of them. Any new messages you save will appear at the top of your drafts. Please note that only messages from the last 3 years are displayed here.",
		thatsallTextSend: "That's all of them. Any new messages you send will appear at the top of your sent items. Please note that only messages from the last 3 years are displayed here.",
		thatsallTextArchived: "That's all of them. Any new messages you archive will show at the top of your archived items. Remember that only messages from the last 3 years are shown here.",
		noMessages: 'No messages.',	
		deleteMessageHeading: 'Are you sure you want to delete this message?',
		deleteMessageBody: "If you delete this message now, you won't be able to recover it.",
		dontDelButton: "No, don't delete",
		delButton: 'Yes, delete',
		messageVal: 'Your message has exceeded the maximum character limit. Please reduce the length of your message then try and send it again.',
		showMore: 'Show more messages',
		backToAccounts: 'Back to accounts',
		pleaseSelect: 'Please select',
		editSavedMessage: 'Edit saved message',
		noSpecificAccount: 'No specific account',
		threeCharLeft: 'Three characters left',
		oneCharLeft: 'One character left',
		maxCharLeft: 'Maximum characters limit reached',
		delete: 'Delete',
		archive: 'Archive',
		unarchive: 'Unarchive',
		moveToInbox: 'Move to inbox',
		unread: 'Unread',
		replyUnread: 'Reply Unread',
		deleteUnread: 'Delete Unread',
		pending: 'Pending',
		sendingMessage: "Sending message...",
		savingMessage: "Saving draft...",

	},
};

export default content;
