
const content = {
	DYB: {
		landingPageTitle: 'Messages',
		landingPageMessage: 'Want to talk to the team at B about your account? Safely share your details in a secure message to get all the help you need.',
		inboxPageTitle: 'Your secure message',
		sentPageTitle: 'Your sent message',
		newMessagePageTitle: 'New secure message',
		replyMessageTitle: 'Reply',
		back: 'Back',
		send: 'Send message',
		maxCharLimit: 'Maximum character limit is three thousand',
		message: 'Message',
		messages: 'Secure messages',
		messageRelatesTo: 'What account’s it about?',
		subject: 'Subject',
		messageSent: 'Message sent',
		messageDeleted: 'Message deleted',
		ok: 'OK',
		draftBody: 'Message saved as draft',
		leaveMessageHeading: 'Oops, your message hasn’t sent yet',
		returnToMessage: 'Continue with message',
		saveDraft: 'Save draft',
		leaveMessageBody: 'Sure you want to leave this page? If you do, your message won’t be sent or saved as a draft.',
		charLeft: 'Characters Left:',
		sorryHeader: 'Something’s gone wrong',
		tryAgain: 'Hmm. Looks like there’s been a technical problem. Why not give it another go?',
		getInTouch: 'Still not working? Try another way to get in touch with the team at B.',
		retry: 'Try again',
		leavePage: 'Leave page',
		accError: 'Oops. You’ll have to choose what account your message is about. General enquiry? Just choose ‘No specific account’.',
		subError: 'Oops. You’ll have to choose a subject for your secure message. ',
		newSecureMessage: 'New secure message',
		thatsallTextInbox: 'That’s all of them. Any new messages the team at B send you will show at the top of your inbox. Remember that only messages from the last 13 months are shown here.',
		thatsallTextDraft: 'That’s all of them. Any new messages you save will show at the top of your drafts. Remember that only messages from the last 13 months are shown here.',
		thatsallTextSend: 'That’s all of them. Any new messages you send will show at the top of your sent items. Remember that only messages from the last 13 months are shown here.',
		noInboxMessages: 'Hmm, looks like you haven’t been sent any secure messages. Remember that only messages from the last 13 months are shown here.',
		noSentMessages: 'Hmm, looks like you haven’t sent any secure messages. Remember that only messages from the last 13 months are shown here.',
		noDraftMessages: 'Hmm, looks like you haven’t saved any secure messages. Remember that only messages from the last 13 months are shown here.',
		deleteMessageHeading: 'Sure you want to delete this message?',
		deleteMessageBody: 'If you delete this message now, you won’t be able to get it back.',
		dontDelButton: 'No, don’t delete',
		delButton: 'Yes, delete',
		messageVal: 'Oops. Looks like your message has gone over the character limit. Try and cut it down a little then give it another go',
		showMore: 'Show more messages',
		backToAccounts: 'Back to accounts',
		faqLink: 'You’ll see all your secure messages from the last 13 months here. For more info about your message history, check out the FAQs in the help section.'
	},

	CB: {
		landingPageTitle: 'Messages',
		landingPageMessage: 'If you want to talk about something specific to you or your account, you can share your details in a secure message. It’s safe and simple, and you’ll get all the help you need.',
		inboxPageTitle: 'Your secure message',
		sentPageTitle: 'Your sent message',
		newMessagePageTitle: 'New secure message',
		replyMessageTitle: 'Reply',
		back: 'Back',
		send: 'Send message',
		maxCharLimit: 'Maximum character limit is three thousand',
		message: 'Message',
		messages: 'Secure messages',
		messageRelatesTo: 'Related account',
		subject: 'Subject',
		messageSent: 'Message sent',
		messageDeleted: 'Message deleted',
		ok: 'OK',
		draftBody: 'Message saved as draft',
		leaveMessageHeading: 'Your message hasn’t been sent yet',
		returnToMessage: 'Continue with message',
		saveDraft: 'Save draft',
		leaveMessageBody: 'If you leave this page now, your message won’t be sent or saved as a draft.',
		charLeft: 'Characters Left:',
		sorryHeader: 'Sorry, there’s been a technical problem',
		tryAgain: 'It looks like something’s gone wrong in the background. Please try again.',
		getInTouch: 'If you’re still having problems, please use another method to get in touch with us.',
		retry: 'Try again',
		leavePage: 'Leave page',
		accError: 'Please select which account your message relates to. If it’s a general enquiry, select ‘No specific account’.',
		subError: 'Please select a subject for your secure message.',
		newSecureMessage: 'New secure message',
		thatsallTextInbox: 'That’s all of them. Any new messages we send you will appear at the top of your inbox. Please note that only messages from the last 13 months are displayed here.',
		thatsallTextDraft: 'That’s all of them. Any new messages you save will appear at the top of your drafts. Please note that only messages from the last 13 months are displayed here.',
		thatsallTextSend: 'That’s all of them. Any new messages you send will appear at the top of your sent items. Please note that only messages from the last 13 months are displayed here.',
		noInboxMessages: 'You haven’t received any secure messages. Please note that only messages from the last 13 months are displayed here.',
		noSentMessages: 'You haven’t sent any secure messages. Please note that only messages from the last 13 months are displayed here.',
		noDraftMessages: 'You haven’t saved any secure messages. Please note that only messages from the last 13 months are displayed here.',
		deleteMessageHeading: 'Are you sure you want to delete this message?',
		deleteMessageBody: 'If you delete this message now, you won’t be able to recover it.',
		dontDelButton: 'No, don’t delete',
		delButton: 'Yes, delete',
		messageVal: 'Your message has exceeded the maximum character limit. Please reduce the length of your message then try and send it again.',
		showMore: 'Show more messages',
		backToAccounts: 'Back to accounts',
		faqLink: 'You’ll see all your secure messages from the last 13 months here. For more information about your message history, please visit the FAQs in the help section.',
	},
};

export default content;
