import keyMirror from 'key-mirror';


export default keyMirror({
    REQUEST_SECURE_MESSAGES: null,
    REQUEST_SECURE_MESSAGES_SUCCESS: null,
    REQUEST_SUBJECTS_SUCCESS:null,
    REQUEST_ACCOUNTS_SUCCESS:null,
    REQUEST_TAB_ACTIVE: null,
    GET_VIEW_MESSAGE_DETAIL: null,
    SET_VIEW_MESSAGE_DETAIL: null,
    UPDATE_SECURE_MESSAGE: null,
    UPDATE_SECURE_MESSAGE_SUCCESS: null,
    CLEAR_TEMP_DATA: null,
    UPDATE_SECURE_MESSAGE_FAILURE: null,
    SEND_MESSAGE_FOR_ACCESSIBILITY:null,
    SEND_MESSAGE_DATA_SUCCESS: null,
    UPDATE_MESSAGE_DATA_SUCCESS: null,
    REQUEST_SECURE_MESSAGES_FAILURE: null,
    REQUEST_SUBJECTS_FAILURE: null,
    ERROR_BACK_BUTTON: null,
    NAVIGATION_REF: null,
    UPDATE_NEW_SECURE_MESSAGE_FAILURE: null,
    UPDATE_SECURE_MESSAGE_DRAFT_FAILURE: null,
})
