import keyMirror from 'key-mirror';


export default keyMirror({
    REQUEST_SECURE_MESSAGES: null,
    REQUEST_SECURE_MESSAGES_SUCCESS: null,
    REQUEST_SUBJECTS_SUCCESS:null,
    REQUEST_ACCOUNTS_SUCCESS:null,
    REQUEST_TAB_ACTIVE: null,
    GET_SECURE_MESSAGES: null,
    GET_VIEW_MESSAGE_DETAIL: null,
    SET_VIEW_MESSAGE_DETAIL: null,
    UPDATE_SECURE_MESSAGE: null,
    UPDATE_SECURE_MESSAGE_SUCCESS: null,
    SEND_MESSAGE_FOR_ACCESSIBILITY:null,
    SEND_MESSAGE_DATA_SUCCESS: null,
    UPDATE_MESSAGE_DATA_SUCCESS: null,
})